In [1]:
# coding:utf-8
from sklearn import preprocessing
import numpy as np
# 初始化数据，每一行表示一个样本，每一列表示一个特征
x = np.array([[0.,-3.,1.],
              [3.,1.,2.],
              [0.,1.,-1.]])

将数据行进行 Min-max 规范化           
新数值 = （原数值 - 极小值）/ (极大值 - 极小值) 这里的极大极小都是整个数组          
我们可以让原始数据投射到指定的空间[min,max]，在 SciKit-Learn 里有个函数 MinMaxScaler 是专门做这个的，它允许我们给定一个最大值和最小值，然后将原始数据投射到 [Min,Max] 中，默认情况下，[Min,Max] 是 [0,1]，也就是把原始数据投放到 [0,1] 范围内。

In [2]:
min_max_scaler = preprocessing.MinMaxScaler()
minmax_x=min_max_scaler.fit_transform(x)
minmax_x

array([[0.        , 0.        , 0.66666667],
       [1.        , 1.        , 1.        ],
       [0.        , 1.        , 0.        ]])

将数据进行 Z-Score 规范化           
新数值 = (原数值 - 均值) / 方差         
Z-Score 规范化之后的数值都符合均值为 0，方差为 1 的正态分布。

In [3]:
scaled_x = preprocessing.scale(x)
scaled_x

array([[-0.70710678, -1.41421356,  0.26726124],
       [ 1.41421356,  0.70710678,  1.06904497],
       [-0.70710678,  0.70710678, -1.33630621]])

小数定标规范化                  
根据数组中最大绝对值的位数，-999 - 88，最大绝对值为 999，小数点会移动 3 位

In [4]:
j = np.ceil(np.log10(np.max(abs(x))))
scaled_x = x/(10**j)
scaled_x

array([[ 0. , -0.3,  0.1],
       [ 0.3,  0.1,  0.2],
       [ 0. ,  0.1, -0.1]])

In [2]:
from sklearn import preprocessing
import numpy as np
min_max_scaler = preprocessing.MinMaxScaler()
a = np.array([[5000.],[58000],[16000]])
minmax_a=min_max_scaler.fit_transform(a)
print(minmax_a)

[[0.        ]
 [1.        ]
 [0.20754717]]
